# IMPORTANT: This file is generated by cucumber-rails - edit at your own peril.
# It is recommended to regenerate this file in the future when you upgrade to a
# newer version of cucumber-rails. Consider adding your own code to a new file
# instead of editing this one. Cucumber will automatically load all features/**/*.rb
# files.

require 'rubygems'
require File.expand_path('../../../test/helper_modules', __FILE__)
include TestHelpers

# Require RSpec expectations, so that we can use them in Cucumber features
require 'rspec/expectations'

require 'cucumber/rails'

# frozen_string_literal: true

# Capybara defaults to CSS3 selectors rather than XPath.
# If you'd prefer to use XPath, just uncomment this line and adjust any
# selectors in your step definitions to use the XPath syntax.
# Capybara.default_selector = :xpath

# Register Chrome visible driver for debugging
Capybara.register_driver :chrome_visible do |app|
  options = Selenium::WebDriver::Chrome::Options.new
  options.binary = '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'
  options.add_argument('--no-sandbox')
  options.add_argument('--disable-dev-shm-usage')
  options.add_argument('--window-size=1280,720')
  options.add_argument('--disable-web-security')
  options.add_argument('--allow-running-insecure-content')
  
  Capybara::Selenium::Driver.new(app, browser: :chrome, capabilities: options)
end

# Use the visible Chrome driver for JavaScript tests to see the browser
Capybara.javascript_driver = :chrome_visible

# Configure screenshot directory
Capybara.save_path = 'tmp/screenshots'


# By default, any exception happening in your Rails application will bubble up
# to Cucumber so that your scenario will fail. This is a different from how
# your application behaves in the production environment, where an error page will
# be rendered instead.
#
# Sometimes we want to override this default behaviour and allow Rails to rescue
# exceptions and display an error page (just like when the app is running in production).
# Typical scenarios where you want to do this is when you test your error pages.
# There are two ways to allow Rails to rescue exceptions:
#
# 1) Tag your scenario (or feature) with @allow-rescue
#
# 2) Set the value below to true. Beware that doing this globally is not
# recommended as it will mask a lot of errors for you!
#
ActionController::Base.allow_rescue = false

# Remove/comment out the lines below if your app doesn't have a database.
# For some databases (like MongoDB and CouchDB) you may need to use :truncation instead.
begin
  DatabaseCleaner.strategy = :transaction
rescue NameError
  raise "You need to add database_cleaner to your Gemfile (in the :test group) if you wish to use it."
end

# You may also want to configure DatabaseCleaner to use different strategies for certain features and scenarios.
# See the DatabaseCleaner documentation for details. Example:
#
#   Before('@no-txn,@selenium,@culerity,@celerity,@javascript') do
#     # { except: [:widgets] } may not do what you expect here
#     # as Cucumber::Rails::Database.javascript_strategy overrides
#     # this setting.
#     DatabaseCleaner.strategy = :truncation
#   end
#
#   Before('not @no-txn', 'not @selenium', 'not @culerity', 'not @celerity', 'not @javascript') do
#     DatabaseCleaner.strategy = :transaction
#   end
#

# Possible values are :truncation and :transaction
# The :transaction strategy is faster, but might give you threading problems.
# See https://github.com/cucumber/cucumber-rails/blob/master/features/choose_javascript_database_strategy.feature
Cucumber::Rails::Database.javascript_strategy = :truncation

# Ensure sphinx directories exist for the test environment
ThinkingSphinx::Test.init
# Configure and start Sphinx without indexing (since we use real-time indices)
# Real-time indices are populated through the daemon API, not through the indexer command
# Using ThinkingSphinx::Test.start_with_autostop would fail because it tries to run indexer
# stop Sphinx at the end of the test suite.
ThinkingSphinx::Test.autostop
ThinkingSphinx::Configuration.instance.render_to_file
ThinkingSphinx::Configuration.instance.controller.start
# This makes tests bit slower, but it's better to use Zeus if wanting to keep sphinx running

# Disable delta indexing as it is not needed and generates unnecessary delay and output
ThinkingSphinx::Deltas.suspend!












# require 'email_spec/cucumber'

# require './spec/support/webmock'

# # Configure Capybara to use Chrome with better compatibility
# require 'capybara/rails'
# require 'selenium-webdriver'

# # Register Chrome headless driver
# Capybara.register_driver :chrome_headless do |app|
#   options = Selenium::WebDriver::Chrome::Options.new
#   options.binary = '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'
#   options.add_argument('--headless')
#   options.add_argument('--no-sandbox')
#   options.add_argument('--disable-dev-shm-usage')
#   options.add_argument('--disable-gpu')
#   options.add_argument('--window-size=1280,720')
#   options.add_argument('--disable-web-security')
#   options.add_argument('--allow-running-insecure-content')
#   options.add_argument('--disable-features=VizDisplayCompositor')
  
#   Capybara::Selenium::Driver.new(app, browser: :chrome, capabilities: options)
# end

# # Register Chrome visible driver for debugging
# Capybara.register_driver :chrome_visible do |app|
#   options = Selenium::WebDriver::Chrome::Options.new
#   options.binary = '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'
#   options.add_argument('--no-sandbox')
#   options.add_argument('--disable-dev-shm-usage')
#   options.add_argument('--window-size=1280,720')
#   options.add_argument('--disable-web-security')
#   options.add_argument('--allow-running-insecure-content')
  
#   Capybara::Selenium::Driver.new(app, browser: :chrome, capabilities: options)
# end

# # Use the visible Chrome driver for JavaScript tests to see the browser
# Capybara.javascript_driver = :chrome_headless

# # Configure screenshot directory
# Capybara.save_path = 'tmp/screenshots'

# # Uncomment this if needed to keep the browser open after the test
# # Capybara::Selenium::Driver.class_eval do
# #   def quit
# #     puts "Press RETURN to quit the browser"
# #     $stdin.gets
# #     @browser.quit
# #   rescue Errno::ECONNREFUSED
# #     # Browser must have already gone
# #   end
# # end

# # Capybara defaults to XPath selectors rather than Webrat's default of CSS3. In
# # order to ease the transition to Capybara we set the default here. If you'd
# # prefer to use XPath just remove this line and adjust any selectors in your
# # steps to use the XPath syntax.
# Capybara.default_selector = :css
# Capybara.ignore_hidden_elements = true
# # These settigs could be in prefork block, but Zeus wouldn't run that, so moved here.
